apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-vue-cn-06-18t11-19-11-frontend.fullname" . }}
  labels:
    {{- include "spring-vue-cn-06-18t11-19-11-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "spring-vue-cn-06-18t11-19-11-frontend.selectorLabels" . | nindent 4 }}
