apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: spring-vue-cn-06-18t11-19-11
spec:
  encryptedData:
    .dockerconfigjson: AgCcvRrsY3HoBk36FZPais0k3T44gyjTJIUdZYrzdo7Pionve556PZSotCCa1eLMg7BWB7uTCxAo8dbpNKb57pNhELI4p/84Fn7K9vRcNiU65Kt7ns5fhyNmsWfEfvO8rAmvM/YsaKlMovGdwfH6EKxt7mdY+05bK0MeNFvjdf0RqqAc0IAFs3pvkxQJNMaL1RHKfVe2TFJYqmnb+JC/HX44RBPq8tKwTvUQS3XV2z7H8DCB4kbK7V48iWB7WUWphfmSZkSoUAeXLHoL1Q8ryquS5JkBWq09cze3ag6OMgJ5WuOfgJzxeXC0vCH6jxt33ob2GWjwhmaXJfOATI+NI5ZAXcP/JUDjpIWahB6L6aUC/azhvUp9JgBeRqCObZ6jETUZ4oC+soIzR9F9PO5cOz/oY48kodGo+qpIhHZhUVIZQmOAATYA9iy/t0H7NYXMzHZa1qRsQ59M/M037Qqu1scKWxZcT8Vtocsyjt57MX8P3sOk954GmqekFSEKPkLYB5SWH/jtl1PvLoDFCmqgCjsQ50bs8st+Oif6oVc9K1BAtb11lp/exPlxpRNl9MaqLhD6bIoiHl0DUw26D/xTXVQJoKH/3kpQmL8ToKt0fCbrCVQ8xWdGANz1Cv9aap1e1PdpeIctYfuAS57dZjzAd0So08hjM/D/TZ8EKI2Jv02b4JklfRMl/s2DlN9Gym7lmyy09DmBqTslpz1Z3wIIKXAB8DnU3MYY8jgmdZKixZLVdAvy69x+mIFsU8CbqKSGRZ0R7YKvoPz5OvpXjWNVL7Ri6ftM5B/vrZbWk2s8ldo4c7fVCm1usQAuf/xOzeIn1J5BR0E1mtlbbRXSbGJbin308AmviP9iFFXnSubW84pavZCdviyxwDu6URGaj2EMCFE8V3SBti27lQrLgHNziPhYivno6tz97vM80IkrV60ZaCyNfPMRiIWwzHWeY74geX8=
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: spring-vue-cn-06-18t11-19-11
    type: kubernetes.io/dockerconfigjson

